theme: jekyll-theme-cayman
title: Wastewater Treatment of Hydraulic Fracturing Fluids via Modeling and Simulation of Anaerobic Digestion and Depolymerization
description: Anaerobic Digestion model & shiny app